# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMap_Instance',
            fields=[
                ('Entry_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Carrier', models.CharField(max_length=200)),
                ('MCC', models.CharField(max_length=200)),
                ('MNC', models.CharField(max_length=200)),
                ('Signal_Type', models.CharField(max_length=200)),
                ('Signal_Strength', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longtitude', models.CharField(max_length=200)),
                ('Upload_Time', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
